# Tomcat
server:
  port: 8082

spring:
  # 环境 dev|test|pro
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      maxFileSize: 104857600 #100MB
      maxRequestSize: 104857600 #100MB
  threads:
    virtual:
      enabled: true # 开启虚拟线程

# mybaits-plus配置
mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: AUTO
      # 默认数据库表下划线命名
      table-underline: true

# 监控信息配置
management:
  endpoints:
    web:
      exposure:
        include: health,threaddump,metrics
  endpoint:
    health:
      show-details: always

logging:
  config: classpath:log4j2.xml
  # 打印sql
  level:
    com.maita.yuedian.vulnerability.library.mapper: debug


system:
  api-signature: '{"417c4f3f30d34043": "5d940d7bb69d428eaf813a243591aba3"}'
  upload-tmp-path: /tmp/upload-path
  download-tmp-path: /tmp/download-path
  gen-password: asdf1234*
  max-token-expire-seconds: 28800
  skip-permission-path: /common/**
  replace-uri-prefix: /vuln-demo
  secret-key: abcdefgabcdefg12
