spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: vuln
    password: vuln123456
    url: jdbc:mysql://mysql:3306/vuln_demo?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
  data:
    redis:
      host: redis
      port: 6379
      password: password123456
      database: 0
      lettuce:
        pool:
          max-active: 8       # 最大连接数
          max-idle: 8         # 最大空闲连接
          min-idle: 0         # 最小空闲连接
          max-wait: -1ms      # 无限等待

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'vuln-demo'
      paths-to-match: '/**'
      packages-to-scan: com.maita.yuedian.vulnerability.library.controller
### knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
    # 是否启用 Host
    enable-host: true
    # 启用 Host 地址
    enable-host-text: "http://123.59.0.83:12082"

system:
  redis-cluster.enable: true