spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: vuln
    password: vuln123456
    url: jdbc:mysql://10.206.0.3:3306/vuln_demo?characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
  data:
    redis:
      cluster:
        nodes: 10.100.4.205:8001,10.100.4.205:8002,10.100.4.205:8003  # 集群节点列表
        max-redirects: 3  # 最大重定向次数
      lettuce:
        cluster:
          refresh:
            adaptive: true  # 自动刷新集群拓扑
            period: 2000    # 刷新间隔（毫秒）
        timeout: 6000       # 超时时间


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'vuln-library'
      paths-to-match: '/**'
      packages-to-scan: com.maita.yuedian.vulnerability.library.controller
### knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
    # 是否启用 Host
    enable-host: true
    # 启用 Host 地址
    enable-host-text: "http://119.45.169.164"
  # 生产环境关闭文档
  production: false

remote:
  auto-test:
    host: http://10.206.0.3:8080
    app-id: 417c4f3f30d34043
    secret-key: 5d940d7bb69d428eaf813a243591aba3

system:
  redis-cluster.enable: true